# Generated by Django 5.1.6 on 2025-03-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_activitylog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="scores",
            new_name="gpa",
        ),
    ]
