# Generated by Django 5.1.6 on 2025-03-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_candidate_program_fit"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="academic_experience",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="projects",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
