# Generated by Django 5.1.6 on 2025-03-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_collegeapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="gpa",
            field=models.FloatField(default=0.0),
        ),
    ]
