# Generated by Django 5.1.6 on 2025-03-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_message_receiver_email_message_receiver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.AddField(
            model_name="message",
            name="receiver_email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
