# Generated by Django 4.2.20 on 2025-04-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_candidate_officer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="program_fit",
            field=models.CharField(
                choices=[
                    ("civil_engineering", "Civil Engineering"),
                    ("mechanical_engineering", "Mechanical Engineering"),
                    ("electrical_engineering", "Electrical Engineering"),
                    ("computer_engineering", "Computer Engineering"),
                    ("chemical_engineering", "Chemical Engineering"),
                    ("biomedical_engineering", "Biomedical Engineering"),
                    ("aerospace_engineering", "Aerospace Engineering"),
                    ("industrial_engineering", "Industrial Engineering"),
                    ("software_engineering", "Software Engineering"),
                    ("math", "Math"),
                    ("science", "Science"),
                    ("business", "Business"),
                    ("arts", "Arts"),
                ],
                default="engineering",
            ),
        ),
    ]
