# Generated by Django 4.2.20 on 2025-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_candidate_program_fit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="program_fit",
            field=models.CharField(
                choices=[
                    ("accounting", "Accounting"),
                    ("aerospace_engineering", "Aerospace Engineering"),
                    ("agriculture", "Agriculture"),
                    ("architecture", "Architecture"),
                    ("art", "Art"),
                    ("biomedical_engineering", "Biomedical Engineering"),
                    ("biology", "Biology"),
                    ("business", "Business"),
                    ("chemical_engineering", "Chemical Engineering"),
                    ("chemistry", "Chemistry"),
                    ("civil_engineering", "Civil Engineering"),
                    ("communications", "Communications"),
                    ("computer_engineering", "Computer Engineering"),
                    ("computer_science", "Computer Science"),
                    ("criminology", "Criminology"),
                    ("data_science", "Data Science"),
                    ("design", "Design"),
                    ("economics", "Economics"),
                    ("electrical_engineering", "Electrical Engineering"),
                    ("english", "English"),
                    ("environmental_science", "Environmental Science"),
                    ("finance", "Finance"),
                    ("graphic_design", "Graphic Design"),
                    ("history", "History"),
                    ("industrial_engineering", "Industrial Engineering"),
                    ("information_technology", "Information Technology"),
                    ("international_relations", "International Relations"),
                    ("journalism", "Journalism"),
                    ("law", "Law"),
                    ("math", "Math"),
                    ("mechanical_engineering", "Mechanical Engineering"),
                    ("medicine", "Medicine"),
                    ("music", "Music"),
                    ("nursing", "Nursing"),
                    ("philosophy", "Philosophy"),
                    ("physics", "Physics"),
                    ("political_science", "Political Science"),
                    ("psychology", "Psychology"),
                    ("public_health", "Public Health"),
                    ("science", "Science"),
                    ("software_engineering", "Software Engineering"),
                    ("sociology", "Sociology"),
                    ("statistics", "Statistics"),
                    ("theater", "Theater"),
                ],
                default="engineering",
            ),
        ),
    ]
