# Generated by Django 4.2.20 on 2025-04-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_alter_candidate_program_fit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("waitlisted", "Waitlisted"),
                ],
                default="pending",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="collegeapplication",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("waitlisted", "Waitlisted"),
                ],
                default="pending",
            ),
        ),
        migrations.AlterField(
            model_name="collegeapplication",
            name="college_name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(),
        ),
    ]
